/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CartRouteImport } from './routes/cart'
import { Route as SplatRouteImport } from './routes/$'
import { Route as CheckoutRouteRouteImport } from './routes/checkout/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as CatalogIndexRouteImport } from './routes/catalog/index'
import { Route as BrandsIndexRouteImport } from './routes/brands/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as ProductProductSlugRouteImport } from './routes/product/$productSlug'
import { Route as BrandsBrandSlugRouteImport } from './routes/brands/$brandSlug'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminBrandsRouteImport } from './routes/admin/brands'
import { Route as AccountWishlistRouteImport } from './routes/account/wishlist'
import { Route as AccountProfileRouteImport } from './routes/account/profile'
import { Route as AccountPasswordRouteImport } from './routes/account/password'
import { Route as AccountNotificationsRouteImport } from './routes/account/notifications'
import { Route as AccountAddressesRouteImport } from './routes/account/addresses'
import { Route as CatalogCategorySlugIndexRouteImport } from './routes/catalog/$categorySlug/index'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as AccountOrdersIndexRouteImport } from './routes/account/orders/index'
import { Route as CheckoutConfirmationOrderIdRouteImport } from './routes/checkout/confirmation/$orderId'
import { Route as CatalogCategorySlugSubcategorySlugRouteImport } from './routes/catalog/$categorySlug/$subcategorySlug'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products/new'
import { Route as AdminOrdersOrderIdRouteImport } from './routes/admin/orders/$orderId'
import { Route as AccountOrdersOrderIdRouteImport } from './routes/account/orders/$orderId'
import { Route as AdminProductsProductIdEditRouteImport } from './routes/admin/products/$productId.edit'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRouteRoute = CheckoutRouteRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CheckoutRouteRoute,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsIndexRoute = BrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const ProductProductSlugRoute = ProductProductSlugRouteImport.update({
  id: '/product/$productSlug',
  path: '/product/$productSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsBrandSlugRoute = BrandsBrandSlugRouteImport.update({
  id: '/brands/$brandSlug',
  path: '/brands/$brandSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBrandsRoute = AdminBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountPasswordRoute = AccountPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountNotificationsRoute = AccountNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AccountRouteRoute,
} as any)
const CatalogCategorySlugIndexRoute =
  CatalogCategorySlugIndexRouteImport.update({
    id: '/catalog/$categorySlug/',
    path: '/catalog/$categorySlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountOrdersIndexRoute = AccountOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const CheckoutConfirmationOrderIdRoute =
  CheckoutConfirmationOrderIdRouteImport.update({
    id: '/confirmation/$orderId',
    path: '/confirmation/$orderId',
    getParentRoute: () => CheckoutRouteRoute,
  } as any)
const CatalogCategorySlugSubcategorySlugRoute =
  CatalogCategorySlugSubcategorySlugRouteImport.update({
    id: '/catalog/$categorySlug/$subcategorySlug',
    path: '/catalog/$categorySlug/$subcategorySlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountOrdersOrderIdRoute = AccountOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AdminProductsProductIdEditRoute =
  AdminProductsProductIdEditRouteImport.update({
    id: '/products/$productId/edit',
    path: '/products/$productId/edit',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/checkout': typeof CheckoutRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/cart': typeof CartRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/password': typeof AccountPasswordRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/users': typeof AdminUsersRoute
  '/brands/$brandSlug': typeof BrandsBrandSlugRoute
  '/product/$productSlug': typeof ProductProductSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/brands/': typeof BrandsIndexRoute
  '/catalog/': typeof CatalogIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/catalog/$categorySlug/$subcategorySlug': typeof CatalogCategorySlugSubcategorySlugRoute
  '/checkout/confirmation/$orderId': typeof CheckoutConfirmationOrderIdRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/catalog/$categorySlug/': typeof CatalogCategorySlugIndexRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/cart': typeof CartRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/password': typeof AccountPasswordRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/users': typeof AdminUsersRoute
  '/brands/$brandSlug': typeof BrandsBrandSlugRoute
  '/product/$productSlug': typeof ProductProductSlugRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/brands': typeof BrandsIndexRoute
  '/catalog': typeof CatalogIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/catalog/$categorySlug/$subcategorySlug': typeof CatalogCategorySlugSubcategorySlugRoute
  '/checkout/confirmation/$orderId': typeof CheckoutConfirmationOrderIdRoute
  '/account/orders': typeof AccountOrdersIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/catalog/$categorySlug': typeof CatalogCategorySlugIndexRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/checkout': typeof CheckoutRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/cart': typeof CartRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/password': typeof AccountPasswordRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/users': typeof AdminUsersRoute
  '/brands/$brandSlug': typeof BrandsBrandSlugRoute
  '/product/$productSlug': typeof ProductProductSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/brands/': typeof BrandsIndexRoute
  '/catalog/': typeof CatalogIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/catalog/$categorySlug/$subcategorySlug': typeof CatalogCategorySlugSubcategorySlugRoute
  '/checkout/confirmation/$orderId': typeof CheckoutConfirmationOrderIdRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/catalog/$categorySlug/': typeof CatalogCategorySlugIndexRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/checkout'
    | '/$'
    | '/cart'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/account/addresses'
    | '/account/notifications'
    | '/account/password'
    | '/account/profile'
    | '/account/wishlist'
    | '/admin/brands'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/users'
    | '/brands/$brandSlug'
    | '/product/$productSlug'
    | '/account/'
    | '/admin/'
    | '/brands/'
    | '/catalog/'
    | '/checkout/'
    | '/account/orders/$orderId'
    | '/admin/orders/$orderId'
    | '/admin/products/new'
    | '/catalog/$categorySlug/$subcategorySlug'
    | '/checkout/confirmation/$orderId'
    | '/account/orders/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/catalog/$categorySlug/'
    | '/admin/products/$productId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/cart'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/account/addresses'
    | '/account/notifications'
    | '/account/password'
    | '/account/profile'
    | '/account/wishlist'
    | '/admin/brands'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/users'
    | '/brands/$brandSlug'
    | '/product/$productSlug'
    | '/account'
    | '/admin'
    | '/brands'
    | '/catalog'
    | '/checkout'
    | '/account/orders/$orderId'
    | '/admin/orders/$orderId'
    | '/admin/products/new'
    | '/catalog/$categorySlug/$subcategorySlug'
    | '/checkout/confirmation/$orderId'
    | '/account/orders'
    | '/admin/orders'
    | '/admin/products'
    | '/catalog/$categorySlug'
    | '/admin/products/$productId/edit'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/checkout'
    | '/$'
    | '/cart'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/account/addresses'
    | '/account/notifications'
    | '/account/password'
    | '/account/profile'
    | '/account/wishlist'
    | '/admin/brands'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/users'
    | '/brands/$brandSlug'
    | '/product/$productSlug'
    | '/account/'
    | '/admin/'
    | '/brands/'
    | '/catalog/'
    | '/checkout/'
    | '/account/orders/$orderId'
    | '/admin/orders/$orderId'
    | '/admin/products/new'
    | '/catalog/$categorySlug/$subcategorySlug'
    | '/checkout/confirmation/$orderId'
    | '/account/orders/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/catalog/$categorySlug/'
    | '/admin/products/$productId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  CheckoutRouteRoute: typeof CheckoutRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  CartRoute: typeof CartRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  BrandsBrandSlugRoute: typeof BrandsBrandSlugRoute
  ProductProductSlugRoute: typeof ProductProductSlugRoute
  BrandsIndexRoute: typeof BrandsIndexRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
  CatalogCategorySlugSubcategorySlugRoute: typeof CatalogCategorySlugSubcategorySlugRoute
  CatalogCategorySlugIndexRoute: typeof CatalogCategorySlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof CheckoutRouteRoute
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/': {
      id: '/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof BrandsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/product/$productSlug': {
      id: '/product/$productSlug'
      path: '/product/$productSlug'
      fullPath: '/product/$productSlug'
      preLoaderRoute: typeof ProductProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$brandSlug': {
      id: '/brands/$brandSlug'
      path: '/brands/$brandSlug'
      fullPath: '/brands/$brandSlug'
      preLoaderRoute: typeof BrandsBrandSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/brands': {
      id: '/admin/brands'
      path: '/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof AdminBrandsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/password': {
      id: '/account/password'
      path: '/password'
      fullPath: '/account/password'
      preLoaderRoute: typeof AccountPasswordRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/notifications': {
      id: '/account/notifications'
      path: '/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AccountNotificationsRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/catalog/$categorySlug/': {
      id: '/catalog/$categorySlug/'
      path: '/catalog/$categorySlug'
      fullPath: '/catalog/$categorySlug/'
      preLoaderRoute: typeof CatalogCategorySlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/orders/': {
      id: '/account/orders/'
      path: '/orders'
      fullPath: '/account/orders/'
      preLoaderRoute: typeof AccountOrdersIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/checkout/confirmation/$orderId': {
      id: '/checkout/confirmation/$orderId'
      path: '/confirmation/$orderId'
      fullPath: '/checkout/confirmation/$orderId'
      preLoaderRoute: typeof CheckoutConfirmationOrderIdRouteImport
      parentRoute: typeof CheckoutRouteRoute
    }
    '/catalog/$categorySlug/$subcategorySlug': {
      id: '/catalog/$categorySlug/$subcategorySlug'
      path: '/catalog/$categorySlug/$subcategorySlug'
      fullPath: '/catalog/$categorySlug/$subcategorySlug'
      preLoaderRoute: typeof CatalogCategorySlugSubcategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders/$orderId': {
      id: '/admin/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/orders/$orderId': {
      id: '/account/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/account/orders/$orderId'
      preLoaderRoute: typeof AccountOrdersOrderIdRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/admin/products/$productId/edit': {
      id: '/admin/products/$productId/edit'
      path: '/products/$productId/edit'
      fullPath: '/admin/products/$productId/edit'
      preLoaderRoute: typeof AdminProductsProductIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AccountRouteRouteChildren {
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountNotificationsRoute: typeof AccountNotificationsRoute
  AccountPasswordRoute: typeof AccountPasswordRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AccountOrdersOrderIdRoute: typeof AccountOrdersOrderIdRoute
  AccountOrdersIndexRoute: typeof AccountOrdersIndexRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountAddressesRoute: AccountAddressesRoute,
  AccountNotificationsRoute: AccountNotificationsRoute,
  AccountPasswordRoute: AccountPasswordRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountWishlistRoute: AccountWishlistRoute,
  AccountIndexRoute: AccountIndexRoute,
  AccountOrdersOrderIdRoute: AccountOrdersOrderIdRoute,
  AccountOrdersIndexRoute: AccountOrdersIndexRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminBrandsRoute: typeof AdminBrandsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminProductsProductIdEditRoute: typeof AdminProductsProductIdEditRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBrandsRoute: AdminBrandsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminProductsProductIdEditRoute: AdminProductsProductIdEditRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface CheckoutRouteRouteChildren {
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  CheckoutConfirmationOrderIdRoute: typeof CheckoutConfirmationOrderIdRoute
}

const CheckoutRouteRouteChildren: CheckoutRouteRouteChildren = {
  CheckoutIndexRoute: CheckoutIndexRoute,
  CheckoutConfirmationOrderIdRoute: CheckoutConfirmationOrderIdRoute,
}

const CheckoutRouteRouteWithChildren = CheckoutRouteRoute._addFileChildren(
  CheckoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  CheckoutRouteRoute: CheckoutRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  CartRoute: CartRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  BrandsBrandSlugRoute: BrandsBrandSlugRoute,
  ProductProductSlugRoute: ProductProductSlugRoute,
  BrandsIndexRoute: BrandsIndexRoute,
  CatalogIndexRoute: CatalogIndexRoute,
  CatalogCategorySlugSubcategorySlugRoute:
    CatalogCategorySlugSubcategorySlugRoute,
  CatalogCategorySlugIndexRoute: CatalogCategorySlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
